import type { CatalogEntry, Category } from './types.js'

export const CATALOG: CatalogEntry[] = [
  {
    name: 'Plane',
    repo: 'makeplane/plane',
    category: 'project_management',
    replaces: ['Jira', 'Linear', 'Asana'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0',
    bestFor: ['Small to mid-size product teams', 'Kanban and sprint workflows'],
    tradeoffs: ['AGPL may require source disclosure for network use', 'Younger ecosystem than Jira'],
    selfHostingComplexity: 'medium',
    notes: 'Modern project management with issues, cycles, and modules.',
    features: ['kanban', 'issues', 'sprints', 'roadmap', 'self-hosting'],
  },
  {
    name: 'Taiga',
    repo: 'kaleidos-ventures/taiga',
    category: 'project_management',
    replaces: ['Jira', 'Trello'],
    deployment: ['self_hosted', 'docker'],
    license: 'MPL-2.0',
    bestFor: ['Agile teams wanting Scrum/Kanban'],
    tradeoffs: ['UI less polished than commercial tools', 'Smaller community than Plane'],
    selfHostingComplexity: 'medium',
    notes: 'Mature agile project management platform.',
    features: ['kanban', 'issues', 'sprints', 'backlog'],
  },
  {
    name: 'Redmine',
    repo: 'redmine/redmine',
    category: 'project_management',
    replaces: ['Jira'],
    deployment: ['self_hosted'],
    license: 'GPL-2.0',
    bestFor: ['Teams needing flexible issue tracking and plugins'],
    tradeoffs: ['Dated UI', 'Plugin maintenance burden'],
    selfHostingComplexity: 'medium',
    notes: 'Long-standing open-source issue tracker with extensive plugins.',
    features: ['issues', 'wiki', 'time-tracking', 'plugins'],
  },
  {
    name: 'Namviek',
    repo: 'hudy9x/namviek',
    category: 'project_management',
    replaces: ['Jira', 'Linear', 'Notion'],
    deployment: ['self_hosted', 'docker'],
    license: 'MIT',
    bestFor: ['Small teams wanting lightweight PM with modern UI'],
    tradeoffs: ['Smaller community', 'Fewer enterprise integrations'],
    selfHostingComplexity: 'low',
    notes: 'Lightweight project management. Verify maintenance activity before adoption.',
    features: ['kanban', 'issues', 'tasks', 'self-hosting'],
  },
  {
    name: 'Supabase',
    repo: 'supabase/supabase',
    category: 'database',
    replaces: ['Firebase', 'Airtable'],
    deployment: ['self_hosted', 'docker', 'cloud', 'managed'],
    license: 'Apache-2.0',
    bestFor: ['Teams building apps with Postgres, auth, and realtime'],
    tradeoffs: ['Self-hosting full stack is complex', 'Managed cloud has usage costs'],
    selfHostingComplexity: 'high',
    notes: 'Open-source Firebase alternative built on PostgreSQL.',
    features: ['database', 'auth', 'storage', 'realtime', 'api'],
  },
  {
    name: 'Appwrite',
    repo: 'appwrite/appwrite',
    category: 'auth',
    replaces: ['Firebase', 'Auth0'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'BSD-3-Clause',
    bestFor: ['Mobile and web backends needing auth and storage'],
    tradeoffs: ['Self-hosting requires ops expertise', 'Feature parity with Auth0 varies'],
    selfHostingComplexity: 'medium',
    notes: 'Backend-as-a-service with auth, databases, and functions.',
    features: ['auth', 'database', 'storage', 'functions'],
  },
  {
    name: 'Plausible',
    repo: 'plausible/analytics',
    category: 'analytics',
    replaces: ['Google Analytics'],
    deployment: ['self_hosted', 'cloud'],
    license: 'AGPL-3.0',
    bestFor: ['Privacy-focused web analytics'],
    tradeoffs: ['Limited compared to GA4 advanced features', 'AGPL obligations'],
    selfHostingComplexity: 'low',
    notes: 'Simple, privacy-friendly analytics. AGPL license — review compliance.',
    features: ['analytics', 'privacy', 'dashboards'],
  },
  {
    name: 'Matomo',
    repo: 'matomo-org/matomo',
    category: 'analytics',
    replaces: ['Google Analytics'],
    deployment: ['self_hosted', 'cloud'],
    license: 'GPL-3.0',
    bestFor: ['Full-featured self-hosted analytics'],
    tradeoffs: ['Heavier resource usage', 'Complex setup for large sites'],
    selfHostingComplexity: 'medium',
    notes: 'Mature analytics platform with extensive plugin ecosystem.',
    features: ['analytics', 'heatmaps', 'goals', 'ecommerce'],
  },
  {
    name: 'PostHog',
    repo: 'PostHog/posthog',
    category: 'analytics',
    replaces: ['Google Analytics', 'Mixpanel', 'Amplitude'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'MIT (with EE components)',
    bestFor: ['Product analytics, feature flags, and session replay'],
    tradeoffs: ['Self-hosting is resource-intensive', 'Some features are enterprise-only'],
    selfHostingComplexity: 'high',
    notes: 'All-in-one product analytics. Check license for enterprise features.',
    features: ['analytics', 'feature-flags', 'session-replay', 'experiments'],
  },
  {
    name: 'Uptime Kuma',
    repo: 'louislam/uptime-kuma',
    category: 'monitoring',
    replaces: ['Datadog', 'Pingdom', 'UptimeRobot'],
    deployment: ['self_hosted', 'docker'],
    license: 'MIT',
    bestFor: ['Simple uptime and status page monitoring'],
    tradeoffs: ['Not a full APM solution', 'Limited enterprise alerting integrations'],
    selfHostingComplexity: 'low',
    notes: 'Easy self-hosted uptime monitoring with status pages.',
    features: ['uptime', 'status-page', 'notifications'],
  },
  {
    name: 'Chatwoot',
    repo: 'chatwoot/chatwoot',
    category: 'customer_support',
    replaces: ['Intercom', 'Zendesk', 'Freshdesk'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'MIT',
    bestFor: ['Omnichannel customer support inbox'],
    tradeoffs: ['Self-hosting requires Ruby/Postgres stack', 'Enterprise features may lag'],
    selfHostingComplexity: 'medium',
    notes: 'Open-source customer engagement platform.',
    features: ['live-chat', 'email', 'crm', 'helpdesk'],
  },
  {
    name: 'Cal.com',
    repo: 'calcom/cal.com',
    category: 'forms',
    replaces: ['Calendly'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0',
    bestFor: ['Scheduling and booking pages'],
    tradeoffs: ['AGPL license considerations', 'Calendar integrations need setup'],
    selfHostingComplexity: 'medium',
    notes: 'Open-source scheduling infrastructure.',
    features: ['scheduling', 'calendar', 'booking'],
  },
  {
    name: 'NocoDB',
    repo: 'nocodb/nocodb',
    category: 'internal_tools',
    replaces: ['Airtable', 'Notion'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0',
    bestFor: ['Spreadsheet-style databases on existing SQL backends'],
    tradeoffs: ['AGPL obligations', 'Performance limits at scale'],
    selfHostingComplexity: 'low',
    notes: 'Turns databases into collaborative spreadsheets.',
    features: ['database', 'spreadsheet', 'api', 'views'],
  },
  {
    name: 'Budibase',
    repo: 'Budibase/budibase',
    category: 'internal_tools',
    replaces: ['Airtable', 'Retool', 'Notion'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'GPL-3.0 / Commercial',
    bestFor: ['Internal tools and low-code apps'],
    tradeoffs: ['GPL license for self-hosted', 'Commercial tier for some features'],
    selfHostingComplexity: 'medium',
    notes: 'Low-code platform for internal business apps.',
    features: ['low-code', 'forms', 'workflows', 'database'],
  },
  {
    name: 'ToolJet',
    repo: 'ToolJet/ToolJet',
    category: 'internal_tools',
    replaces: ['Retool', 'Airtable'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0 / Commercial',
    bestFor: ['Building internal dashboards and tools'],
    tradeoffs: ['AGPL for community edition', 'Learning curve for complex apps'],
    selfHostingComplexity: 'medium',
    notes: 'Low-code internal tool builder.',
    features: ['low-code', 'dashboards', 'api-integrations'],
  },
  {
    name: 'Directus',
    repo: 'directus/directus',
    category: 'cms',
    replaces: ['Contentful', 'Airtable'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'GPL-3.0 / BSL',
    bestFor: ['Headless CMS and data platform'],
    tradeoffs: ['License model changed — verify current terms', 'Resource usage for large datasets'],
    selfHostingComplexity: 'medium',
    notes: 'Headless CMS wrapping any SQL database. Review current license.',
    features: ['cms', 'api', 'database', 'admin-ui'],
  },
  {
    name: 'Strapi',
    repo: 'strapi/strapi',
    category: 'cms',
    replaces: ['Contentful', 'WordPress'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'MIT (with EE)',
    bestFor: ['Headless CMS for content APIs'],
    tradeoffs: ['Some features enterprise-only', 'Plugin compatibility varies by version'],
    selfHostingComplexity: 'medium',
    notes: 'Popular headless CMS with REST/GraphQL APIs.',
    features: ['cms', 'api', 'media', 'roles'],
  },
  {
    name: 'Ghost',
    repo: 'TryGhost/Ghost',
    category: 'cms',
    replaces: ['WordPress', 'Medium', 'Substack'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'MIT',
    bestFor: ['Publishing and newsletter-focused sites'],
    tradeoffs: ['Focused on publishing, not general CMS', 'Membership features need Stripe setup'],
    selfHostingComplexity: 'low',
    notes: 'Professional publishing platform.',
    features: ['blog', 'newsletter', 'membership', 'seo'],
  },
  {
    name: 'Listmonk',
    repo: 'knadh/listmonk',
    category: 'email',
    replaces: ['Mailchimp', 'ConvertKit'],
    deployment: ['self_hosted', 'docker'],
    license: 'AGPL-3.0',
    bestFor: ['Self-hosted newsletters and mailing lists'],
    tradeoffs: ['No built-in email delivery — needs SMTP provider', 'AGPL obligations'],
    selfHostingComplexity: 'low',
    notes: 'High-performance mailing list manager. Requires external SMTP.',
    features: ['email', 'newsletter', 'campaigns'],
  },
  {
    name: 'n8n',
    repo: 'n8n-io/n8n',
    category: 'automation',
    replaces: ['Zapier', 'Make'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'Sustainable Use License / Commercial',
    bestFor: ['Workflow automation and integrations'],
    tradeoffs: ['License restricts competing hosted services', 'Complex workflows need maintenance'],
    selfHostingComplexity: 'medium',
    notes: 'Fair-code workflow automation. Review Sustainable Use License.',
    features: ['automation', 'integrations', 'workflows', 'webhooks'],
  },
  {
    name: 'Metabase',
    repo: 'metabase/metabase',
    category: 'analytics',
    replaces: ['Tableau', 'Looker', 'Google Analytics'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0 / Commercial',
    bestFor: ['Business intelligence and dashboards'],
    tradeoffs: ['AGPL for OSS edition', 'Heavy for very large datasets'],
    selfHostingComplexity: 'medium',
    notes: 'BI tool for SQL databases.',
    features: ['dashboards', 'sql', 'reports', 'embedding'],
  },
  {
    name: 'Keycloak',
    repo: 'keycloak/keycloak',
    category: 'auth',
    replaces: ['Auth0', 'Okta'],
    deployment: ['self_hosted', 'docker', 'kubernetes'],
    license: 'Apache-2.0',
    bestFor: ['Enterprise SSO and identity management'],
    tradeoffs: ['Complex configuration', 'Resource-heavy'],
    selfHostingComplexity: 'high',
    notes: 'Full-featured identity and access management.',
    features: ['auth', 'sso', 'oauth', 'saml'],
  },
  {
    name: 'Outline',
    repo: 'outline/outline',
    category: 'documentation',
    replaces: ['Notion', 'Confluence'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'BSL-1.1',
    bestFor: ['Team wikis and knowledge bases'],
    tradeoffs: ['BSL license — review terms', 'Requires cloud storage backend'],
    selfHostingComplexity: 'medium',
    notes: 'Modern team wiki. Review Business Source License.',
    features: ['wiki', 'docs', 'collaboration', 'search'],
  },
  {
    name: 'Formbricks',
    repo: 'formbricks/formbricks',
    category: 'forms',
    replaces: ['Typeform', 'SurveyMonkey'],
    deployment: ['self_hosted', 'docker', 'cloud'],
    license: 'AGPL-3.0 / Commercial',
    bestFor: ['Surveys and in-app feedback'],
    tradeoffs: ['AGPL for self-hosted', 'Smaller ecosystem than Typeform'],
    selfHostingComplexity: 'medium',
    notes: 'Experience management and survey platform.',
    features: ['forms', 'surveys', 'feedback', 'analytics'],
  },
]

export const SAAS_TOOLS = [
  'Jira', 'Linear', 'Notion', 'Airtable', 'HubSpot', 'Intercom', 'Zendesk',
  'Datadog', 'Vercel', 'Netlify', 'Zapier', 'Typeform', 'Calendly', 'Slack',
  'Google Analytics', 'Asana', 'Trello', 'Firebase', 'Auth0', 'Mailchimp',
  'Contentful', 'WordPress', 'Retool', 'Make', 'Freshdesk', 'Pingdom',
]

export function findByRepo(repo: string): CatalogEntry | undefined {
  const normalized = repo.toLowerCase().replace(/^https?:\/\/github\.com\//, '').replace(/\/$/, '')
  return CATALOG.find((e) => e.repo.toLowerCase() === normalized)
}

export function findByName(name: string): CatalogEntry | undefined {
  return CATALOG.find((e) => e.name.toLowerCase() === name.toLowerCase())
}

export function findByReplaces(saas: string): CatalogEntry[] {
  const normalized = saas.toLowerCase()
  return CATALOG.filter((e) =>
    e.replaces.some((r) => r.toLowerCase() === normalized || r.toLowerCase().includes(normalized)),
  )
}

export function findByCategory(category: Category): CatalogEntry[] {
  return CATALOG.filter((e) => e.category === category)
}

export function parseRepoSlug(input: string): string {
  return input
    .replace(/^https?:\/\/github\.com\//, '')
    .replace(/\.git$/, '')
    .replace(/\/$/, '')
    .trim()
}

export function repoDisplayName(repo: string, catalog?: CatalogEntry): string {
  if (catalog) return catalog.name
  const slug = parseRepoSlug(repo)
  const parts = slug.split('/')
  if (parts.length >= 2) {
    const name = parts[1]
    return name.charAt(0).toUpperCase() + name.slice(1)
  }
  return slug
}